% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Apr-2020 23:20:00
%  MATLAB version: 9.5.0.1033004 (R2018b) Update 2
% -------------------------------------------------------------------
                                                

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [-10.510444657489176 -9.4924211147701865 144.70837072366808];
smiData.RigidTransform(1).angle = 2.0943951023931953;
smiData.RigidTransform(1).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(1).ID = 'B[Link1-2:-:Link2-2]';
smiData.RigidTransform(2).translation = ...
  [132.00000000000114 -67.799999999999969 -1.9895196601282805E-13];
smiData.RigidTransform(2).angle = 2.0943951023931935;
smiData.RigidTransform(2).axis = [-0.57735026918962506 -0.57735026918962529 ...
                                  -0.57735026918962684];
smiData.RigidTransform(2).ID = 'F[Link1-2:-:Link2-2]';
smiData.RigidTransform(3).translation = ...
  [0 0 0];
smiData.RigidTransform(3).angle = 2.0943951023931953;
smiData.RigidTransform(3).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(3).ID = 'B[BaseBracket-1:-:Link1-2]';
smiData.RigidTransform(4).translation = ...
  [-10.510444657489177 42.707578885229964 289.20837072366726];
smiData.RigidTransform(4).angle = 3.1401849173675503E-16;
smiData.RigidTransform(4).axis = [-1 0 -0];
smiData.RigidTransform(4).ID = 'F[BaseBracket-1:-:Link1-2]';
smiData.RigidTransform(5).translation = ...
  [-132.00000000000011 -67.5 -2.3727737525596365E-13];
smiData.RigidTransform(5).angle = 2.0943951023931935;
smiData.RigidTransform(5).axis = [-0.57735026918962506 -0.57735026918962506 ...
                                  -0.57735026918962717];
smiData.RigidTransform(5).ID = 'B[Link2-2:-:Link3-1]';
smiData.RigidTransform(6).translation = ...
  [125.00000000000034 60.000000000000057 1.4921397450962104E-13];
smiData.RigidTransform(6).angle = 2.0943951023931935;
smiData.RigidTransform(6).axis = [-0.57735026918962518 -0.57735026918962506 ...
                                  -0.57735026918962717];
smiData.RigidTransform(6).ID = 'F[Link2-2:-:Link3-1]';
smiData.RigidTransform(7).translation = ...
  [-112.0000000000001 -39.001000000000033 -1.3096709326830973E-13];
smiData.RigidTransform(7).angle = 2.0943951023931935;
smiData.RigidTransform(7).axis = [-0.57735026918962506 -0.57735026918962506 ...
                                  -0.57735026918962717];
smiData.RigidTransform(7).ID = 'B[Link3-1:-:Link4-1]';
smiData.RigidTransform(8).translation = ...
  [-1.6058265828178264E-12 -153.00100000000003 5.6843418860808015E-14];
smiData.RigidTransform(8).angle = 2.0943951023931953;
smiData.RigidTransform(8).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  -0.57735026918962584];
smiData.RigidTransform(8).ID = 'F[Link3-1:-:Link4-1]';
smiData.RigidTransform(9).translation = ...
  [39.000999999999955 0 0];
smiData.RigidTransform(9).angle = 2.0943951023931953;
smiData.RigidTransform(9).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(9).ID = 'B[Link4-1:-:Link5-2]';
smiData.RigidTransform(10).translation = ...
  [-1.4210854715202004E-14 -162.00100000000009 7.1054273576009987E-15];
smiData.RigidTransform(10).angle = 2.0943951023931957;
smiData.RigidTransform(10).axis = [-0.57735026918962573 -0.57735026918962573 ...
                                   -0.57735026918962562];
smiData.RigidTransform(10).ID = 'F[Link4-1:-:Link5-2]';
smiData.RigidTransform(11).translation = ...
  [39.000999999999991 -9.0000000000000071 0];
smiData.RigidTransform(11).angle = 2.0943951023931953;
smiData.RigidTransform(11).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(11).ID = 'B[Link5-2:-:Link6-1]';
smiData.RigidTransform(12).translation = ...
  [3.5528246608834122E-15 -96.000999999999991 1.4210854715202004E-14];
smiData.RigidTransform(12).angle = 2.0943951023931953;
smiData.RigidTransform(12).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(12).ID = 'F[Link5-2:-:Link6-1]';
smiData.RigidTransform(13).translation = ...
  [0 0 0];
smiData.RigidTransform(13).angle = 0;
smiData.RigidTransform(13).axis = [0 0 0];
smiData.RigidTransform(13).ID = 'B[BaseBracket-1:-:]';
smiData.RigidTransform(14).translation = ...
  [0 0 0];
smiData.RigidTransform(14).angle = 0;
smiData.RigidTransform(14).axis = [0 0 0];
smiData.RigidTransform(14).ID = 'F[BaseBracket-1:-:]';
smiData.Solid = struct;
smiData.Solid(1).mass = 1.4773559338963831;
smiData.Solid(1).CoM = [0.014279966279667253 32.890554634759866 -0.81951106197130785 ...
                        ];
smiData.Solid(1).MoI = [2480.4352493289803 3435.8038976032271 2537.2878004084423 ...
                        ];
smiData.Solid(1).PoI = [-18.880332638675092 -0.217670538327728 0.5945323946769383 ...
                        ];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'BaseBracket*:*默认';
smiData.Solid(2).mass = 0.0129712547554152;
smiData.Solid(2).CoM = [0 11.479927348100436 0.030834805185941696];
smiData.Solid(2).MoI = [5.5122566339041228 10.432468349342102 5.5205941985793805 ...
                        ];
smiData.Solid(2).PoI = [-0.0014079097774669976 0 0];
smiData.Solid(2).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'Link6*:*默认';
smiData.Solid(3).mass = 0.200711934819471;
smiData.Solid(3).CoM = [-9.1801022760498139 -13.389179215802775 -0.00026579403749275052 ...
                        ];
smiData.Solid(3).MoI = [344.82081131521335 426.872021170499 474.446111919054 ...
                        ];
smiData.Solid(3).PoI = [-3.5925192652529765E-5 0.0019573639462339694 27.605396209300764 ...
                        ];
smiData.Solid(3).color = [1 1 1];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Link4*:*默认';
smiData.Solid(4).mass = 0.54268272343778245;
smiData.Solid(4).CoM = [-10.506124700425284 34.137716312352289 158.94344971381216 ...
                        ];
smiData.Solid(4).MoI = [1165.1346721323687 1097.7135263982248 993.94303005141774 ...
                        ];
smiData.Solid(4).PoI = [-68.15743019399946 0.02996262661054027 -0.07314833096389381 ...
                        ];
smiData.Solid(4).color = [1 1 1];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Link1*:*默认';
smiData.Solid(5).mass = 0.926396369879602;
smiData.Solid(5).CoM = [9.5995734775174633 7.6353888141221384 -0.00019242853079775272 ...
                        ];
smiData.Solid(5).MoI = [1413.3444125091348 6969.29391451983 7179.8017449750005 ...
                        ];
smiData.Solid(5).PoI = [-0.0023867829437466234 0.020735120294673 -401.17041024794594 ...
                        ];
smiData.Solid(5).color = [1 1 1];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Link3*:*默认';
smiData.Solid(6).mass = 0.20071193481947122;
smiData.Solid(6).CoM = [-9.1801022760497712 -22.389179215802766 -0.00026579403749240141 ...
                        ];
smiData.Solid(6).MoI = [344.820811315215 426.87202117049156 474.44611191906125 ...
                        ];
smiData.Solid(6).PoI = [-3.5925192669743392E-5 0.0019573639462221125 27.605396209298256 ...
                        ];
smiData.Solid(6).color = [1 1 1];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'Link5*:*默认';
smiData.Solid(7).mass = 1.847806300117012;
smiData.Solid(7).CoM = [0.015098022301386679 -8.3614082647447585 0];
smiData.Solid(7).MoI = [3605.59754954134 21128.313983657223 21561.447005128382 ...
                        ];
smiData.Solid(7).PoI = [-9.6999032309551141E-7 0.72502751288955747 -0.23326841336530205 ...
                        ];
smiData.Solid(7).color = [1 1 1];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'Link2*:*默认';
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = -90.000000000000028;
smiData.RevoluteJoint(1).ID = '[Link1-2:-:Link2-2]';
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = -90;
smiData.RevoluteJoint(2).ID = '[BaseBracket-1:-:Link1-2]';
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = 0;
smiData.RevoluteJoint(3).ID = '[Link2-2:-:Link3-1]';
smiData.RevoluteJoint(4).Rz = struct;
smiData.RevoluteJoint(4).Rz.Pos = 0;
smiData.RevoluteJoint(4).ID = '[Link3-1:-:Link4-1]';
smiData.RevoluteJoint(5).Rz = struct;
smiData.RevoluteJoint(5).Rz.Pos = 90;
smiData.RevoluteJoint(5).ID = '[Link4-1:-:Link5-2]';
smiData.RevoluteJoint(6).Rz = struct;
smiData.RevoluteJoint(6).Rz.Pos = -180;
smiData.RevoluteJoint(6).ID = '[Link5-2:-:Link6-1]';

